# -------------------------------------------------------------------------------------------------------
# Custom properties (not part of Spring)
# These property names (and values, of course) can be changed to your liking.
# -------------------------------------------------------------------------------------------------------
application:
  default-page-limit: 25
  cors:
    allowed-origins: "http://*.localhost"

# -------------------------------------------------------------------------------------------------------
# Spring properties
# -------------------------------------------------------------------------------------------------------
server:
  port: 8080
  servlet:
    context-path: /

# -------------------------------------------------------------------------
# OpenApi/SpringDoc/Swagger properties
# -------------------------------------------------------------------------
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  model-converters:
    pageable-converter:
      enabled: true
  swagger-ui:
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha

# -------------------------------------------------------------------------
# Actuator properties
# -------------------------------------------------------------------------
management:
  endpoint:
    health:
      probes:
        enabled: true

# -------------------------------------------------------------------------
# Spring properties
# -------------------------------------------------------------------------

spring:
  application:
    name: kafka-zen-lab-102-consumer-api

  # Modify these as desired.
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    serialization:
      indent_output: false
    deserialization:
      fail_on_unknown_properties: false

  jpa:
    show-sql: true
    properties:
      hibernate:
        id:
          new_generator_mappings: false

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    # -------------------------------------------------------------------------------------------
    # Hikari connection pool properties. See: https://github.com/brettwooldridge/HikariCP
    # -------------------------------------------------------------------------------------------
    hikari:
      connection-timeout: "2000"
      maximum-pool-size: 20
      minimum-idle: 2
      pool-name: "springboot-hikari-cp"
      max-lifetime: 1000000
      data-source-properties:
        cachePrepStmts: true
        # Size of the prepared statement cache
        prepStmtCacheSize: 250
        # Maximum length of a statement the driver will cache
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchStatements: true
        cacheResultsSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false


  # -------------------------------------------------------------------------------------------
  # Kafka
  # -------------------------------------------------------------------------------------------
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      bootstrap-servers: "${spring.kafka.bootstrap-servers}"
      client-id: "${spring.application.name}"
      enable-auto-commit: false
      group-id: "${spring.application.name}"
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      properties:
        spring.json.trusted.packages: "zen.lab.*"
        spring.json.value.default.type: "zen.lab.consumer.adapters.edge.inbound.messages.model.ClickEventMessage"
    listener:
      ack-mode: MANUAL_IMMEDIATE
      client-id: "${spring.application.name}"
      concurrency: 5
      missing-topics-fatal: false

# -------------------------------------------------------------------------
# Logging
# -------------------------------------------------------------------------
logging:
  level:
    root: INFO
