/*
 * Copyright 2026 [CopyrightOwner]
 */
package zen.lab.consumer.adapters.port.inbound.validation;

import static java.lang.annotation.ElementType.*;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

import jakarta.validation.Constraint;
import jakarta.validation.Payload;
import java.lang.annotation.Documented;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;

/**
 * Constraint that verifies a {@code String} value has the format of a resource identifier
 * generated by {@code ResourceIdGenerator}.
 *
 * <p>A valid resource ID is:
 * <ul>
 *   <li>Exactly {@link zen.lab.consumer.domain.shared.ResourceIdFormat#RESOURCE_ID_LENGTH}
 *       (27) characters long</li>
 *   <li>Composed exclusively of alphanumeric characters ({@code [A-Za-z0-9]})</li>
 * </ul>
 *
 * <p>Apply this annotation to REST path variables and request-body fields that are
 * expected to contain a resource identifier. See {@code ResourceIdValidator} for the
 * validation logic.
 *
 * @see ResourceIdValidator
 */
// See https://www.baeldung.com/spring-mvc-custom-validator

@Target({METHOD, FIELD, PARAMETER})
@Retention(RUNTIME)
@Constraint(validatedBy = ResourceIdValidator.class)
@Documented
public @interface ResourceId {
    String message() default "{ResourceId.invalid}";

    Class<?>[] groups() default {};

    Class<? extends Payload>[] payload() default {};
}
