version: '3.8'

services:
    application:
        container_name: "kafka-zen-lab-102-consumer-api_api"
        image: "kafka-zen-lab-102-consumer-api:latest"
        ports:
            - "8080:8080"
